version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: dataon_postgres
    environment:
      POSTGRES_USER: dataon
      POSTGRES_PASSWORD: dataonpassword
      POSTGRES_DB: dataon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 